### ISSUE TITLE
Support for erasing inner triangles

### ISSUE THREAD

**Issue by KuDeSnik33ra** [artem-ogre/CDT#1]
Is there any possibility to detect, if triangles are inner - this is common scenario in gis triangulation, for example, boost::geometry::model::polygon can have one outer vertex ring and multiple inner vertex rings - for gaps in it. I tried to add inner vertex and boundaries to CDT - it produced triangles in the gaps. Is there any posiibility to remove them? 

I think, the easy way to add such functionality is to mark verts as inner on adding them, and then remove triangles, containing only inner verts.

**Comment by artem-ogre** [comment]
To my knowledge, triangulation with holes usually requires specifying holes as a collection of polygons. The approach you suggest will often work but will fail in a general case.
Imagine situation like this:
![image](https://user-images.githubusercontent.com/7488293/75548235-1163c200-5a2d-11ea-8fc0-c23c64c5135e.png)
You can see that there are many valid triangles that contain only inner vertices (and one triangle that contains only inner vertices of same hole).

If you have hole polygons defined, a work-around you could do is to triangulate each hole polygon separately and then remove resulting "hole-triangles" from original triangulation. Please let me know if this makes sense for you. :)

**Comment by KuDeSnik33ra** [comment]
So, i need to create separate Triangulation for every inner poly and buffer forbidden triangles via vert indexes? Will triangles be the same in such sceneario (if verts order will be the same)?

**Comment by artem-ogre** [comment]
I have an idea for the work-around. And I will try to add support for it in the library when I get some time.

The idea is something like this:
```
#include "CDT.h"
using Triangulation = CDT::Triangulation<float>;

Triangulation cdt(...);
cdt.insertVertices(/* points */);
cdt.insertEdges(/* all edges: outer and inner boundaries */);

Triangulation cdtInner = cdt; // copy triangulation
cdtInner.fixedEdges.clear();
// line below should be cheap since all edges are already in the triangulation
cdtInner.insertEdges(/*only inner boundaries*/);

cdtInner.eraseOuterTriangles(); // erase until outer border
cdt.eraseOuterTriangles(); // erase until inner border
/* final vertices */ = cdt.vertices;
/* final triangles is set difference of cdt.triangles without cdtInner.triangles*/
// set difference could be done like this:  https://stackoverflow.com/questions/22710331/performing-set-difference-on-unordered-sets
```

Code above is from the top of my head, I did not have time to check if it actually works, but I think it should.

**Comment by KuDeSnik33ra** [comment]
It works, thanks!

**Comment by KuDeSnik33ra** [comment]
Are indexes order in triangles stable for both Trianglulations? Or I need to check for same triangles via indexes - order independantly?

**Comment by artem-ogre** [comment]
The indices are not stable. But both vectors of triangle should have them in same order (for example [1,2,3,4,5,6,7] and [2,4,7]). So it should be possible to find the difference efficiently (set difference suggested above will not work though).

**Comment by KuDeSnik33ra** [comment]
Sorry, I mean vertex order in triangle, not triangle index in triangles vector. Do I need to check:
`isInnerTri = [&cdtInner](const CDT::Triangle& tri)
 {
     for (auto& innerTri : cdtInner.triangles)
     {
           if (tri.vertices == innerTri.vertices)
                return true;
     }
     return false;
};
`
or I have to check it order independent:
`
isInnerTri = [&cdtInner](const CDT::Triangle& tri)
{
     for (auto& innerTri : cdtInner.triangles)
     {
          int match = 0;
          for (auto& vert0 : tri.vertices)
          {
                 for (auto& vert1 :  innerTri.vertices)
                 {
                       if(vert0 == vert1)
                       {
                             match++;
                             break;
                       }
                 }
          }
           if (match == 3)
                return true;
      }
     return false;
}
`

**Comment by artem-ogre** [comment]
Vertex indices should not be changed, when removing triangles. First version should work :)

**Comment by artem-ogre** [comment]
![image](https://user-images.githubusercontent.com/7488293/75802103-747e8d00-5d7c-11ea-9468-de01fab9fb87.png)
I've implemented a way to automatically deal with holes in the model: 04035ef73c3e65bb4701c010a5c404e0dd41dbaa

It grows until outer boundary. Triangles outside outer boundary are removed. Then it grows until next boundary. Triangles between are kept. Then it grows again, this time removing triangles and so on.

This way as long as constraint boundaries are closed it is possible to handle _'hole-island-hole'_ topologies.

Please give it a try and let me know if it works well for you :)
Надеюсь, сработает хорошо.

**Comment by artem-ogre** [comment]
I will close this issue as solved.

**Comment by KuDeSnik33ra** [comment]
I have tested this, it works. Thanks!
