### ISSUE TITLE
3D?

### ISSUE THREAD

**Issue by cdcseacave** [artem-ogre/CDT#10]
Such a cool library, unfortunately only for 2D. Can't be generalized to 3D easily?

**Comment by artem-ogre** [comment]
Hi, 

Do you mean creating constrained Delaunay tetrahedralizations?
I don’t know how easy/comlex such a generalization is, so any input and contributions are welcome. Do you have any good references or algorithm descriptions in mind?

Hypothetically since 3d versions of predicates are available, inserting points should be rather straightforward. Inserting constraints could be more difficult in 3d though.

Thanks for the interest and feedback.

**Comment by cdcseacave** [comment]
I am a simple user, I am not familiarize with the theory behind. I know [TetGen](http://wias-berlin.de/software/tetgen) implements it in 3D, and there is a paper describing it: http://doi.acm.org/10.1145/2629697

**Comment by artem-ogre** [comment]
Thanks, I will look into it. It definitely looks like it needs some effort.  So I can't promise anything anytime soon.
Leaving this issue open as any contributions are welcome.

**Comment by anishsingh935** [comment]
hi can I work on this issue

**Comment by artem-ogre** [comment]
Thanks, @anishsingh935 

Let me know if you need any help. Please be aware that this might be a sizable effort: up to a point that it makes more sense to have constrained tetrahedralization as a stand alone lib based on CDT. Perhaps CDT3D or CDTet :)

**Comment by GenieTim** [comment]
Hi @anishsingh935 , may I kindly ask: what is the status, where you able to progress, is there a CDT3D or CDTet now?

**Comment by artem-ogre** [comment]
@GenieTim
To my knowledge nothing happened

**Comment by xiaolong7** [comment]
Hi, can CDT be used for 2D triangulation of points in 3D space, like 3D surface reconstruction of point clouds?

**Comment by district10** [comment]
I'm looking for a way to triangulate a pointcloud. Here's an example:

A highway road surface:

https://github.com/artem-ogre/CDT/assets/5262037/55229370-1461-4ff6-827d-386789a994c9

sample data: [segments.pcd.zip](https://github.com/artem-ogre/CDT/files/12320797/segments.pcd.zip)

For a workaround, I may 1) segmentize pointcloud (colored by segment); 2) call CDT with ignoring z; 3) merge each segment's CDT into one.

It'll be great if CDT supports surface pointcloud.

**Comment by artem-ogre** [comment]
Hi, @district10 
If I understood correctly you ask how to triangulate the areas where roads overlap at different height levels?

**Comment by district10** [comment]
@artem-ogre Yes. It's like building a CDT along the way, without botherings of overpass/underpass.

**Comment by artem-ogre** [comment]
One may either use another algorithm for surface reconstruction or do some hacks. Maybe constrained DT is not a good tool for the job in your case.
