### ISSUE TITLE
Random shuffling not compatible with c++17

### ISSUE THREAD

**Issue by petrasvestartas** [artem-ogre/CDT#104]
Hi,

Can you add some checks for the function that use random shuffling dependent on C++ version? The one you use is only compatible till C++14.

**Comment by here-abarany** [comment]
The last tagged release uses the deprecated (and removed in C++17) `std::random_shuffle()` function. This was replaced in a later revision (available on master but not in a release tag), though there are still some issues with the shuffling logic as described in #97.

**Comment by petrasvestartas** [comment]
This part is causing error and I tempoarily changed to the following code:
![image](https://user-images.githubusercontent.com/18013985/195086876-51b48c65-55a8-4ae8-a731-430e9162066e.png)

**Comment by artem-ogre** [comment]
As @here-abarany mentioned it's fixed on `master`. I stopped doing releases for CDT (as it's more work) and instead suggest to live on the latest master branch. When I get time, I will make one last release that would say not to use pinned releases to make it clear for the users :)

**Comment by petrasvestartas** [comment]
Understood, using the git clone instead of release. I close this issue.
