### ISSUE TITLE
edges Parameter not in CDT::Triangulation

### ISSUE THREAD

**Issue by Sum80** [artem-ogre/CDT#108]
When using the code.

#include "CDT.h"
CDT::Triangulation<double> cdt;
cdt.insertVertices(/* points */);
cdt.eraseSuperTriangle();
/* access triangles */ = cdt.triangles;
/* access vertices */ = cdt.vertices;
/* access boundary edges */ = cdt.edges;

edges is not a member of CDT::Triangulation.

**Comment by artem-ogre** [comment]
Hi, @Sum80,

Thank you for creating the issue. There was a change: edges are calculated on request. Please use `extractEdgesFromTriangles` to calculate edges from triangles. I will need to update the documentation to reflect this.

**Comment by artem-ogre** [comment]
I have updated the README.md:
- fixed edges only are still available via `fixedEdges`
- all edges can be calculated on demand
```cxx
/* access boundary (fixed) edges */ = cdt.fixedEdges;
/* calculate all edges (on demand) */ = CDT::extractEdgesFromTriangles(cdt.triangles);
```
