### ISSUE TITLE
KDTree namespace conflict

### ISSUE THREAD

**Issue by tysoni** [artem-ogre/CDT#110]
I have a large project I'm testing CDT in, and there happens to be a class in the project named KDTree which causes CDT to generate all kinds of unrelated errors during compilation due to the naming conflict between the KDTree class and CDT's KDTree namespace.

Nesting the KDTree namespace of the CDT library inside the CDT namespace solves the problem. It probably makes sense to have all CDT classes/namespaces nested inside the CDT namespace....KDTree is the only one I see outside of it.

**Comment by artem-ogre** [comment]
Thank you for opening the issue @tysoni!

Yes, definitely, this is reasonable to do. It sounds like you already made it to work. Would you mind making a PR?

**Comment by tysoni** [comment]
Unfortunately I'm pretty limited in my knowledge/usage of github at the moment, so I'm only able to report :)

**Comment by artem-ogre** [comment]
@tysoni I merged the fix. Please let me know if it worked for you.

**Comment by tysoni** [comment]
Perfect, thank you!
