### ISSUE TITLE
insertEdgeIteration will crash if iTopo value is 'noNeighbor'

### ISSUE THREAD

**Issue by tysoni** [artem-ogre/CDT#111]
Ran into a case where insertEdgeIteration can generate an unhandled exception. Line 524 of Triangulation.hpp can return a value of 'noNeighbor' which is then used (without a bounds check) to access an array by index - instant crash.

![itopo](https://user-images.githubusercontent.com/2181360/204051116-4f765c87-3e95-4f0a-9a3e-c600bb2cb465.png)

**Comment by artem-ogre** [comment]
Do you have code/input example that can reproduce the issue?

**Comment by tysoni** [comment]
Sure, here's the code:

    CDT::Triangulation<float> cdt;
    cdt.insertVertices(cdtVerts); 
    cdt.insertEdges(cdtEdges);  
    cdt.eraseOuterTrianglesAndHoles();
    
And attached are the contents of the cdtVerts and cdtEdges arrays, in the format:

    vert1x
    vert1y
    vert2x
    vert2y
    ....

and 

    edge1v1
    edge1v2
    edge2v1
    edge2v2
    ....

You should be able to read the values in line-by-line to fill the arrays.

[cdtDebugEdges.txt](https://github.com/artem-ogre/CDT/files/10095064/cdtDebugEdges.txt)
[cdtDebugVerts.txt](https://github.com/artem-ogre/CDT/files/10095065/cdtDebugVerts.txt)

**Comment by artem-ogre** [comment]
Hi @tysoni 
Thanks for opening the issue. CDT does not support duplicated (exactly) vertices and intersecting edges (can be automatically resolved with `IntersectingConstraintEdges::Resolve` but without guaranties).

The input you provided has duplicates. `FindDuplicates` returns:
```cpp
duplicates = 
 [0] = 428
 [1] = 429
 [2] = 430
 [3] = 431
 [4] = 432
 [5] = 433
 [6] = 434
 [7] = 435
```

After fixing it with `CDT::RemoveDuplicates` and using `CDT::IntersectingConstraintEdges::Resolve` triangulation finishes successfully.
![cdt_screenshot](https://user-images.githubusercontent.com/7488293/207155043-feb6f94e-0ade-4c46-8963-6b8802f67b5b.png)

**Comment by artem-ogre** [comment]
I'm closing this, please let me know if you think this should be re-open.

**Comment by tysoni** [comment]
Thanks @artem-ogre. I had pre-processed my polygons to remove duplicate verts that are next to each other...but wasn't aware that duplications anywhere in the polygon - even across non-adjacent edges - were a problem. Will make sure to avoid that in the future. I appreciate you taking the time to investigate this!
