### ISSUE TITLE
VertexInsertionOrder::Randomized is not thread safe

### ISSUE THREAD

**Issue by tysoni** [artem-ogre/CDT#112]
Sorry for the rapid-fire issue reporting...I'm testing CDT in a high performance geometry fracturing library that's using CDT for slice cap triangulation...so I'm putting CDT through the wringer against hundreds of thousands of test cases on complex polygons.

Anyways, VertexInsertionOrder::Randomized is not thread safe (multiple CDT operations cannot be run simultaneously) because your random_shuffle function relies on a static instance of an mt19937 generator that may be unsafely accessed by multiple concurrent threads. 

A solution might be to allow users to provide their own pointer to a generator as an argument in the CDT constructor. That way local generators can be constructed in each thread running CDT operations...

**Comment by artem-ogre** [comment]
#97

**Comment by AmazingBean** [comment]
six six six

**Comment by AmazingBean** [comment]
six six six

**Comment by artem-ogre** [comment]
@AmazingBean 
> six six six

what do you mean?

**Comment by artem-ogre** [comment]
Fixed.
