### ISSUE TITLE
How to compile and use under windows ? Thank you

### ISSUE THREAD

**Issue by AmazingBean** [artem-ogre/CDT#114]
How to solve the following errors under win10?

-- Building for: Visual Studio 14 2015
-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.18363.
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working CXX compiler: D:/vs/VC/bin/cl.exe
-- Check for working CXX compiler: D:/vs/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CDT_USE_BOOST is OFF
-- CDT_USE_AS_COMPILED_LIBRARY is ON
-- CDT_USE_64_BIT_INDEX_TYPE is ON
-- CDT_ENABLE_TESTING is OFF
**-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed**
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found suitable version "1.9.5 (2f6875a5ca481a69a6f32650c77a667f87d25e88)", minimum required is "1.9") found components:  doxygen missing components:  dot
-- Doxygen found: adding documentation target.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/cmake-3.14.7-win64-x64/bin/CDT-master/CDT/build

**Comment by artem-ogre** [comment]
This part is CMake detecting compiler support for `[[deprecated]]` attribute feature. It does not indicate an issue: the generation was successful.

**Comment by artem-ogre** [comment]
FYI the same thing happens in CDT CI builds: https://github.com/artem-ogre/CDT/actions/runs/3360296325/jobs/5569311167#step:5:114
