### ISSUE TITLE
Would you please illustrate the algorithm of eraseOuterTriangles() and eraseOuterTrianglesAndHoles()

### ISSUE THREAD

**Issue by GeoGroup** [artem-ogre/CDT#121]
Thanks for your excellent code. I am a liitle confused about the  algorithm of eraseOuterTriangles() and eraseOuterTrianglesAndHoles(). For example,  the growToBoundary in eraseOuterTriangles  make me confused. Would you please add some illustration. As for the eraseOuterTriangles, what is the difference between this method and InPolygon?

Many Thanks.

**Comment by artem-ogre** [comment]
Hello @GeoGroup,

The removal of triangles works the following way on the high level:
- It starts by adding triangles adjacent to super-triangle vertices as seeds for the selection
- Then triangle-walking algorithm incrementally adds neighboring triangles to the selection if the shared edge is not a constraint (boundary)
- At the end all triangles outside the outer boundary are selected
- If we remove this triangles from the triangulation we get the result of `eraseOuterTriangles`
- The process can then be repeated by seeding with triangles that are across the boundary from the outer triangles to calculate 'layers'
- Removing every second layer starting with the outer layer is what `eraseOuterTrianlgesAndHoles` does

Please let me know if you need any further clarification.

**Comment by GeoGroup** [comment]
Thank for your reply. My problem is solved. Your solution is very simple and efficient!
