### ISSUE TITLE
Is it true that all triangles have same direction?

### ISSUE THREAD

**Issue by Hotege** [artem-ogre/CDT#129]
I've tried CDT library and I notice that all triangles have same direction in my example.
![capture](https://user-images.githubusercontent.com/9608943/235416283-ebf23514-ec1a-4f51-87fd-11302e23a63d.PNG)
(All triangles are clockwise in this coordinate system in the picture)
But I don't know whether CDT can ensure that or not. I didn't find any illustration about it.

**Comment by Islam0mar** [comment]
see https://github.com/artem-ogre/CDT#algorithm `Post-conditions:`.

**Comment by Hotege** [comment]
> see https://github.com/artem-ogre/CDT#algorithm `Post-conditions:`.

My bad. I just read the comment in the source codes.
