### ISSUE TITLE
how can I control vertex count?

### ISSUE THREAD

**Issue by hyungshin-park** [artem-ogre/CDT#131]
Can I increase the number of vertices? If possible, which parameters should I modify? 
Is it possible to fill the inside of the boundary as densely as shown in the left image?
![image](https://github.com/artem-ogre/CDT/assets/11537213/e3bb7c0d-bd94-4635-bbc3-b0bdeb8246af)

**Comment by artem-ogre** [comment]
Hello, @hyungshin-park 

CDT only does triangulation and does not have any refinement available. Maybe you could calculate the additional points yourself and then insert them into the triangulation.

See also: #7

**Comment by hyungshin-park** [comment]
Thanks, Then the left image must have been calculated the additional points, right?

**Comment by artem-ogre** [comment]
Yes, on the left image all the points are part of the input.

**Comment by artem-ogre** [comment]
Sorry for posting in the old thread. Ruppert refinement finally landed in: #225
