### ISSUE TITLE
Could not find vertex triangle intersected by edge

### ISSUE THREAD

**Issue by qtbui159** [artem-ogre/CDT#134]
I try to use [tri.txt](https://github.com/qtbui159/static_files/blob/main/tri.txt) to get triangles：
1. cdt.insertVertices
2. cdt.insertEdges 

But when it comes to 2，prompting "Could not find vertex triangle intersected by edge"，could you pls advise what should I do next?

**Comment by artem-ogre** [comment]
Did you check for duplicates with `CDTp::FindDuplicates`?

**Comment by artem-ogre** [comment]
It does have duplicates, you can try opening it in the visualizer, it detects and fixes the duplicates. The result looks like this:
![cdt_screenshot](https://github.com/artem-ogre/CDT/assets/7488293/f69ac39c-6e8f-46ce-a239-8c71b6e6d894)

**Comment by artem-ogre** [comment]
Also see the functionality for detecting and fixing the duplicates in the [README](https://github.com/artem-ogre/CDT#implementation-details)

**Comment by qtbui159** [comment]
> CDT does not support duplicates but provides functionality for detecting and fixing them.

Thx for replying @artem-ogre . It works well with CDT::RemoveDuplicatesAndRemapEdges.
