### ISSUE TITLE
Missing inline

### ISSUE THREAD

**Issue by ldcMasa** [artem-ogre/CDT#144]
Hello,

In file CDT_Utils.hpp, the function touchesSuperTriangle should be defined as
 CDT_INLINE_IF_HEADER_ONLY
bool touchesSuperTriangle(const Triangle& t)

Otherwise, it leads to duplicate symbol errors.

**Comment by artem-ogre** [comment]
Thanks @ldcMasa. I will fix it ASAP.

**Comment by artem-ogre** [comment]
Fixed and did a new release. Thank you again.

**Comment by artem-ogre** [comment]
Ah, I rushed the wrong fix first. Could you please verify that the latest master fixes the problem now?

**Comment by ldcMasa** [comment]
Yes, it works fine, thanks.
