### ISSUE TITLE
[1.3.3] Issue with edge insertion (CDT::IntersectingConstraintEdges::Resolve)

### ISSUE THREAD

**Issue by egladil86** [artem-ogre/CDT#148]
There seems to be a problem with edge insertion in [1.3.3] that worked fine in [1.3.0].

It triggers the assertion `assert(triStart != noNeighbor);` in Triangulation.hpp (line 1959) in Debug,
or dereferences `triangles[noNeighbor]` in Release.

There are two intersecting edges AB and MN.
CDT inserts the intersection point X and splits the two edges accordingly:
```
AB -> {AX, XB}
MN -> {MX, XN}
```
The problem occurs, when an edge BC (concatenating AB) is inserted,
because the previous split set `m_vertTris[B] = noNeighbor` (only in [1.3.3]).

I was not able to reproduce this with a minimal example.
Please find attached an example program triggering the issue:
[CdtEdgeInsertIssue.zip](https://github.com/artem-ogre/CDT/files/12879570/CdtEdgeInsertIssue.zip)

By default it uses [1.3.3] and crashes.
Configuring cmake with `-DCDT_TAG=1.3.0` the triangulation works fine.

If this is not an code issue, but a problem with my input data, I would like to know how to determine that.

**Comment by artem-ogre** [comment]
Hello, @egladil86,

Thank you very much for opening the issue. Could you please format input as a text file that I could load into CDT visualizer?
You can find some examples here: https://github.com/artem-ogre/CDT/tree/master/visualizer/data

The format is
```
VertexCount EdgeCount
X Y
...
X Y
Start_Index EndIndex
```
for example a single triangle is written as:
```
3 3
-1 0
 1 0
 0 1
0 1
1 2
2 0

```

**Comment by artem-ogre** [comment]
There is a chance that the bug is introduced after 1.3.0

**Comment by egladil86** [comment]
Thanks for the fast reply.
Here are the inputs in the visualizer format:
[CdtEdgeInsertIssue.txt](https://github.com/artem-ogre/CDT/files/12882260/CdtEdgeInsertIssue.txt)

**Comment by egladil86** [comment]
@artem-ogre Yes the fix works for this and all my other testcases.
Thank you very much the fast solution.

**Comment by artem-ogre** [comment]
Thank you @egladil86. The fix is merged, I added you are on the contributors list.
