### ISSUE TITLE
Tiny compilation warning (VS2019)

### ISSUE THREAD

**Issue by LeoPizzo1** [artem-ogre/CDT#163]
Using the library and defining CDT_USE_64_BIT_INDEX_TYPE, during the compilation I get this warning:
CDT\include\Triangulation.hpp(1497,32): warning C4244: 'initializing': conversion from 'const _Ty' to 'CDT::Index', possible loss of data

It refers to:
```
        const Index iDupe = v1 == v   ? t.vertices[0]
                            : v2 == v ? t.vertices[1]
                                      : t.vertices[2];
```
where `Index `is an `unsigned char`, and `t.vertices `vector contains an `unsigned long long`.

**Comment by artem-ogre** [comment]
Thanks for spotting and reporting @LeoPizzo1 :smiley:

**Comment by artem-ogre** [comment]
Did it fix the warning? 
Side note: Do you really need 64 bit indices? I think 32bit is enough for 99.99% use cases

**Comment by artem-ogre** [comment]
could you check if the warnings a gone?

**Comment by LeoPizzo1** [comment]
Warnings gone, thanks!
