### ISSUE TITLE
How to obtain the vertices inside the boundary composed with some edges?

### ISSUE THREAD

**Issue by pan3rock** [artem-ogre/CDT#171]
I made Delaunay triangulation without constraints given some vertices. Under some criteria, I get several closed boundaries composed with some edges and want to find all vertices inside one certain boundary (including those on the boundary). I tried to use the k-means method to perform clustering, but in some cases it failed. Is there any other simple way to accomplish it?

An example like below, there are two closed boundaries. I've known all triangles/vertices inside boundaries and edges for each boundary. How to determine which vertices are inside/on the certain boundary?
![image](https://github.com/artem-ogre/CDT/assets/44249464/1453050a-5966-4cd2-b722-945ad1448e50)

**Comment by artem-ogre** [comment]
I’m away from the keyboard. Did you solve it?

**Comment by pan3rock** [comment]
I tried to use the distance between vertices and center of boundaries to determine which those vertices belong to. Sometimes it fails, e.g., when two groups of boundaries are connected with one vertex, I have to find other ways to avoid the operation. Is there some simpler replacement using the boundary directly?

**Comment by pan3rock** [comment]
Hi, do you have some ideas about this?
