### ISSUE TITLE
A case that failed in triangulation

### ISSUE THREAD

**Issue by pan3rock** [artem-ogre/CDT#172]
I encountered some failed cases that said "Duplicate vertex detected: # is a duplicate of #". After checking it, I found it's because of the triangulation at the last iteration in my codes. There is a simple example below. It's kind of like #166. I don't know the reason, is it a bug or due to invalid points?

The vertices are
```txt
    0      0.000010000000      0.000010000000
    1      1.000000000000      0.000000000000
    2      0.999990000000      0.099990000000
    3      0.000000000000      0.100000000000
    4      0.500005000000      0.000005000000
    5      0.500000000000      0.050000000000
    6      0.499995000000      0.099995000000
```
The generated triangles are
```txt
    5    0    4
    0    5    3
    5    2    6
    2    3    6
    3    5    6
    2    5    1
    4    1    5
```
The triangle (2, 3, 6) is the red line, a flat triangle.
![image](https://github.com/artem-ogre/CDT/assets/44249464/6b929eeb-c35c-4942-a862-1a9544428908)

**Comment by Islam0mar** [comment]
>  2      0.999990000000      0.099990000000
>  3      0.000000000000      0.100000000000
>  6      0.499995000000      0.099995000000

It's clear these points aren't collinear from their `y` values! you can round your input points to match with your need.

**Comment by artem-ogre** [comment]
Yes, it is the duplicate. The points are not exactly on the same line. Exactly means that if you solve orient2d predicate: the determinant is exactly zero. It is easy to see that 0.09999 != 0.1 or 0.099995.

**Comment by pan3rock** [comment]
@artem-ogre @Islam0mar  The three points are collinear.
```python
x1, y1 = 0.999990000000, 0.099990000000 # 2
x2, y2 = 0.000000000000, 0.100000000000 # 3
x3, y3 = 0.499995000000, 0.099995000000 # 6

def collinear(x1, y1, x2, y2, x3, y3):
    a = x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)
 
    if (a == 0):
        print("Yes")
    else:
        print("No")
collinear(x1, y1, x2, y2, x3, y3)
```
The output is `Yes`.

**Comment by artem-ogre** [comment]
This code is likely returning “Yes” because of the floating point rounding errors. This is exactly the problem that solved by the robust geometric predicates (RGPs). CDT is using RGPs. There are a lot of very good RGP explanations that can be found online.

**Comment by pan3rock** [comment]
Thanks. I tried the RGPs provided by [predicates](https://github.com/danshapero/predicates/tree/master). The value of orient2d of the three points is also 0. I'll check it again tomorrow and find if there is another mistake.

**Comment by artem-ogre** [comment]
What about this one used in CDT?
https://github.com/artem-ogre/CDT/blob/58f34da24b438bd17629450fcec189ccb181dc9f/CDT/include/predicates.h#L115

**Comment by pan3rock** [comment]
I used the orient2d in CDT, the results are below:
```
    5    0    4     2.49973e-02
    0    5    3     4.99945e-02
    5    2    6     2.49973e-02
    2    3    6     6.93847e-18
    3    5    6     2.49973e-02
    2    5    1     4.99945e-02
    4    1    5     2.49973e-02
```
The value for (2, 3, 6) is 6.93847e-18. It may be a precision problem.

**Comment by artem-ogre** [comment]
Are all of these results for `adaptive::orient2d` from predicates used in CDT?

**Comment by pan3rock** [comment]
Yes.
```c++
auto v1 = predicates::adaptive::orient2d(x1, y1, x2, y2, x3, y3);
```

**Comment by artem-ogre** [comment]
In the last examples change of sign is due to changing the order of points (which changes winding). It however should not change from zero to negative in my understanding. What are the coordinates of points (15, 8, 3)?

Was your other claim that orient2d should return zero for (2,3,6) compared to another RGP implementation.

And last claim is that there are triangles in final triangulation for which adaptive::orient2d is zero?

I would appreciate the minimal reproducers. In that case I could take a closer look when I’m back at the keyboard.

**Comment by pan3rock** [comment]
A [demo](https://github.com/pan3rock/CDT-issue-172) is provided. You can observe the change from zero to other values. Another RGP implementation is also included. In the first case, they are the same, but the second is different.

the double precision is 1e-16, is that 1.0e-18 should be regarded as zero? Like my job, the update of new vertices is from some splitted edges (x_new = (x_i + x_j) / 2.0), the location has an error of 1.0e-16, is it possible that's the reason to produce such problem?
```
git clone https://github.com/pan3rock/CDT-issue-172.git
cd CDT-issue-172
git submodule init
git submodule update
mkdir build
cd build
cmake ..
make -j4
../bin/demo1
```
my output:
```
(6, 4, 7):      2.16840e-19
(6, 7, 4):     -2.16840e-19
(7, 4, 6):     -2.16840e-19
another predicates:      2.16840e-19
another predicates:     -2.16840e-19
another predicates:     -2.16840e-19
(1, 2, 3):     -8.67362e-19
(1, 3, 2):      4.33681e-19
(3, 2, 1):      0.00000e+00
another predicates:     -4.33681e-19
another predicates:      4.33681e-19
another predicates:      4.33681e-19
```

**Comment by artem-ogre** [comment]
Only exactly zero should be considered as zero. E.g.,  smallest representable positive double 2.225E-307 should be considered positive.

**Comment by artem-ogre** [comment]
What happens if you change `fmt::print` to display the actual value of double?

**Comment by pan3rock** [comment]
you mean to print the double value with full precision?

```c++
fmt::print("({:d}, {:d}, {:d}): {}\n", v[0], v[1], v[2], v1);
```
output:
```
(6, 4, 7): 2.168404344971009e-19
(6, 7, 4): -2.168404344971009e-19
(7, 4, 6): -2.168404344971009e-19
another predicates: 2.168404344971009e-19
another predicates: -2.168404344971009e-19
another predicates: -2.168404344971009e-19
(1, 2, 3): -8.673617379884035e-19
(1, 3, 2): 4.336808689942018e-19
(3, 2, 1): 0
another predicates: -4.336808689942018e-19
another predicates: 4.336808689942018e-19
another predicates: 4.336808689942018e-19
```

**Comment by artem-ogre** [comment]
Doesn’t look right. I will check (1,2,3)-case next week.

**Comment by artem-ogre** [comment]
Can't reproduce on gcc and clang:
https://godbolt.org/z/s5MqjrTvf

**Comment by artem-ogre** [comment]
It turns out that predicate breaks when `-Ofast` flag is used, works fine with `-O3`
https://godbolt.org/z/Kx9xrcETs

**Comment by artem-ogre** [comment]
from `Ofast` [docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Ofast):

> Disregard strict standards compliance. -Ofast enables all -O3 optimizations. It also enables optimizations that are not valid for all standard-compliant programs. It turns on -ffast-math, -fallow-store-data-races and the Fortran-specific -fstack-arrays, unless -fmax-stack-var-size is specified, and -fno-protect-parens. It turns off -fsemantic-interposition. 

`ffast-math` is not supported by robust predicates.

**Comment by artem-ogre** [comment]
For the (2, 3, 6) both predicates agree that points are collinear with `O3`.
My guess is that if `Ofast` flag is removed, the triangulation will not contain flat triangles.

**Comment by pan3rock** [comment]
Great, you're right. It's `Ofast`. Thanks a lot.
