### ISSUE TITLE
Question about m_vertTris

### ISSUE THREAD

**Issue by LeoPizzo1** [artem-ogre/CDT#173]
Ciao,

I am still struggling with the insertion of the non regular grid.
Everithing seemd to work, but in the last days I got some exceptions, always at line 1494 of trianhulation.hpp.
It seems that the m_vertTris vector is not the one it is expecting.

I tried to reverse engineer the CDT::detail::generateGridVertices without big success.
At first I was thinking it was the smaller triangle index a vertex is connected to, but it is not true.
It seems it is related somehow (in the grid case) to the row it belongs.
i.e.
To obtain this grid:
![image](https://github.com/artem-ogre/CDT/assets/73240053/45c3f82a-3d98-474e-ad53-adec4434be6d)

I set xres = 3 and yres = 4 and initializeWithRegularGrid returns the triangles:
0 1 4 
1 5 4 
1 2 5 
2 6 5 
2 3 6 
3 7 6 
4 5 8 
5 9 8 
5 6 9 
6 10 9 
6 7 10 
7 11 10 
8 9 12 
9 13 12 
9 10 13 
10 14 13 
10 11 14 
11 15 14 
12 13 16 
13 17 16 
13 14 17 
14 18 17 
14 15 18 
15 19 18 

And this m_vertTris vector:
0
0
2
4
6
6
8
10
12
12
14
16
18
18
20
22
18
19
21
23

I see that triangle 0 is connected with vertex 0 1 4 , but the m_vertTris[3] is 4 and not 0. 

Can you please give me some hints on what is the triangle number to insert?

Thanks a lot!

**Comment by artem-ogre** [comment]
Hi, @LeoPizzo1,
unfortunately I have very little time to look into this. If you can provide small and simple example reproducing the problem and describe what is the desired outcome, this will increase the chances of me looking into it. Unfortunately, I cannot promise anything.
