### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by sampotter** [artem-ogre/CDT#181]
Just a heads up that there's another, very closely aligned library with exactly the same name: https://github.com/MarcoAttene/CDT

See also: https://github.com/MarcoAttene/CDT/issues/8

**Comment by artem-ogre** [comment]
Well, it’s a three letter abbreviation. I’m fine with that 🙂

**Comment by sampotter** [comment]
@artem-ogre Sorry to hear that you think this issue is trivial and not worth your time, but please consider the following:

1. Your CDT exists because of licensing issues and difficulties working with the author of Triangle.
2. The other CDT exists partly because it's an academic project improving on TetGen, but I assume the licensing issues with TetGen are also responsible for the decision to invent time in that project. We would prefer not to shell out for a TetGen license---presumably many others feel the same.
3. Triangle and TetGen work beautifully together, especially in the context of finite elements and other numerical methods (my domain); the same will be true of CDT and CDT.
4. If CDT and CDT reach maturity and are used widely, it's inevitable they will be used together (we are exploring doing exactly this at the moment).
5. CDT and CDT are C++ libraries using CMake as a build system. Even if they don't exist now, eventual name collisions between CDT and CDT are highly likely.

For us, discussing CDT and CDT is already very confusing because they have the same name. It seems like a good thing to try to facilitate what the inevitable users of your library will try to accomplish (build surface meshes and then tetrahedralize their interiors).

I appreciate that you're on parental leave and don't have patience for issues like this that seem small. Please consider that this issue is not actually that insignificant.

Thanks!

**Comment by artem-ogre** [comment]
Sorry if my reply seemed dismissive. I did not intend it this way.

The issue description is not specific about what exactly is a problem and what solutions are suggested. Is it a "could-be-a-problem" or "there-is-a-problem" situation? If latte: the above-mentioned specifics are helpful. If former: name collisions are unpleasant, but there are ways to deal with them. C++, CMake, or package managers (e.g., vcpkg or Conan) all have tools and methods for solving name collisions. I don't expect it to become a blocker in the future. What do you think?

**Comment by artem-ogre** [comment]
For resolving ambiguity one could always use _artem-ogre/CDT_ and _MarcoAttene/CDT_.
