### ISSUE TITLE
Are these intersecting edges being handled correctly?

### ISSUE THREAD

**Issue by mungaihehe** [artem-ogre/CDT#182]
Each edge drawn separately (no CDT)

Ignore the interior triangles of the edges; only the convex hull of the edge is passed to cdt

![Screenshot 2024-07-01 at 09 34 13](https://github.com/artem-ogre/CDT/assets/46344262/8d82be83-8180-4024-ac8e-9beea7762f4e)

Conforming - cdt.conformToEdges

![Screenshot 2024-07-01 at 09 35 02](https://github.com/artem-ogre/CDT/assets/46344262/b3b7f709-4bd3-44c3-83a1-d9b1d53128ee)

Constrained - cdt.insertEdges

![Screenshot 2024-07-01 at 09 35 54](https://github.com/artem-ogre/CDT/assets/46344262/4aaaa4ff-2e1f-4567-a590-6c60a8f4c2f8)

Seems to me like those criss crossing triangles are not supposed to be there. Any insights?

**Comment by artem-ogre** [comment]
Please provide the inputs and the code calling CDT.
