### ISSUE TITLE
Self intersecting boundaries

### ISSUE THREAD

**Issue by LeoPizzo1** [artem-ogre/CDT#20]
Sometimes it happens that edge loops are (self) intersecting, due to various description errors.
Now the library fails to remove the outer loops, returning no triangles.
It could be interesting to get a result, even if wrong in this case.

**Comment by artem-ogre** [comment]
Could you provide a small (preferably) example of the input you are talking about?

**Comment by LeoPizzo1** [comment]
Here you can find two tests, ne very easy (but exaggerated by intention), where a "butterfly" is created.
The other one, on the contrary, is the "real life" case.
I know I can fix the problem adding a vertex at the intersection and splitting the edges accordingly, but it takes time...
My idea is that it is not to obtain a correct tessellation, but to obtain the triangles up to the edges, even if the resulting tessellation is not "well formed" and self intersecting.
To display it would be enough.

[real_life_test.txt](https://github.com/artem-ogre/CDT/files/5459672/real_life_test.txt)
[test_exagerated.txt](https://github.com/artem-ogre/CDT/files/5459673/test_exagerated.txt)

**Comment by LeoPizzo1** [comment]
Here, fo your info, the real life working case:
[real_life_working.txt](https://github.com/artem-ogre/CDT/files/5459794/real_life_working.txt)
