### ISSUE TITLE
Is Edge ordering required?

### ISSUE THREAD

**Issue by digitalutopia1** [artem-ogre/CDT#22]
I'm having an issue with processing a shape that contains a single hole - The shape and hole have defined edges. However, when I proceed to `insertEdges` I get a runtime error at the close of `intersectedTriangle`

code: 
```
Triangulation cdt = Triangulation(CDT::FindingClosestPoint::ClosestRandom, 10);
cdt.insertVertices(edgeVertsF[i]);
cdt.insertEdges(edges[i]);
cdt.eraseOuterTrianglesAndHoles();

```
data:
https://pastebin.com/aq4eXVA8

I've ensured that there are no duplicate points, and the edges reference the appropriate points. The only thing I haven't done is order/separate the outer and inner edges. 

Using Visual Studio 2019 and CDT as header only.

**Comment by artem-ogre** [comment]
Hi there, I am away from computer for some days. Is this issue still valid?

**Comment by digitalutopia1** [comment]
No - I'm pretty sure it was just on my end. Just to be sure, I did put the edges in order, and in the process made sure the edge indices lined up with the verts, and it worked fine.

**Comment by artem-ogre** [comment]
And as to the order of edges: it should not matter.
