### ISSUE TITLE
Failure in tessellation

### ISSUE THREAD

**Issue by LeoPizzo1** [artem-ogre/CDT#24]
Ciao, the attached file fails to remove the outer boundary.
[CDTTessellationBoundsNotScaled (2).txt](https://github.com/artem-ogre/CDT/files/5602446/CDTTessellationBoundsNotScaled.2.txt)

**Comment by artem-ogre** [comment]
You have intersecting constraint edges:
<img src="https://user-images.githubusercontent.com/7488293/100351303-892a4180-2feb-11eb-8851-54188a7ce6ea.png" alt="Overview" height="300"/>
Here's zoom-in adding edges constraint 89-92:
<img src="https://user-images.githubusercontent.com/7488293/100351484-cabaec80-2feb-11eb-8478-b4324f73577b.png" alt="89" height="170"/><img src="https://user-images.githubusercontent.com/7488293/100351488-cb538300-2feb-11eb-9124-9076b527437e.png" alt="90" height="170"/><img src="https://user-images.githubusercontent.com/7488293/100351491-cbec1980-2feb-11eb-9eb7-f94074528258.png" alt="91" height="170"/><img src="https://user-images.githubusercontent.com/7488293/100351493-cc84b000-2feb-11eb-913a-cdfed0acd98c.png" alt="92" height="170"/>

**Comment by artem-ogre** [comment]
FYI here's fixed file: [CDTTessellationBoundsNotScaled.2.txt](https://github.com/artem-ogre/CDT/files/5603048/CDTTessellationBoundsNotScaled.2.txt)

**Comment by LeoPizzo1** [comment]
I see. Wrong tolology, sorry : dicn't recognized the problem.
