### ISSUE TITLE
Commercial using

### ISSUE THREAD

**Issue by Pin80** [artem-ogre/CDT#35]
Please, leave a contact in order to obtain a license on your code in commercial purposes.

**Comment by artem-ogre** [comment]
Hello, @Pin80

CDT is available under MPL 2 license which is a permissive copyleft license. It is possible to use it for commercial purposes: see the [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/).

Is MPL 2 not sufficient for your needs?

**Comment by artem-ogre** [comment]
I would love to know by whom and where CDT is used :) If you don’t feel like sharing it here, my gmail is “artem.ogre”.

Does this answer your questions?
