### ISSUE TITLE
Flat Element

### ISSUE THREAD

**Issue by JaredCrean2** [artem-ogre/CDT#41]
I encountered a possible bug while computing a constrained triangulation.  Here is a plot of the constraints:

![mesh_constraints](https://user-images.githubusercontent.com/10292902/126831034-e03ebca6-24d5-43a4-b132-c8fa2399f2f3.png)

Here is a plot of the triangulation generated by CDT:

![mesh_output](https://user-images.githubusercontent.com/10292902/126831093-0bbf2766-1c00-4ae2-b884-953caab5eb1b.png)

The problem is that the three vertices on the upper-right side are put into a single element.  Here are the angles of each element

```
triangle 0 has angles 104.51, 32.0194, 43.4705
triangle 1 has angles 29.3741, 51.7046, 98.9213
triangle 2 has angles 8.53774e-07, 0, 180
triangle 3 has angles 70.2043, 70.6423, 39.1533
triangle 4 has angles 73.9633, 65.8872, 40.1495
triangle 5 has angles 29.7778, 50.5047, 99.7174
triangle 6 has angles 64.009, 78.8855, 37.1055
triangle 7 has angles 97.3523, 51.7375, 30.9102
triangle 8 has angles 1.20742e-06, 8.53774e-07, 180
```

Notice the angles of triangle 2 (listed in degrees).

A minimal reproduce-able example is attached.  It contains
  * mesh_constraints_verts.txt : the coordinates of the vertices
  * mesh_constraints_edges.txt : the indices of vertices that form constrained edges
  * test4.cc : source file that loads the above two files, used CDT to compute the triangulation, computes the edge angle, and writes triangulation files mesh_output_verts.txt and mesh_output_triangles.txt
  * fout: output from running test4 (including the edge angles shown above)
  * the plots shown above

To compile test4.cc, it only needs to find the CDT include directory.
[cdt.tar.gz](https://github.com/artem-ogre/CDT/files/6870844/cdt.tar.gz)

**Comment by JaredCrean2** [comment]
Here is another, somewhat simpler, example:

Constraints
![mesh_constraints](https://user-images.githubusercontent.com/10292902/126846459-86cdf62a-eb64-4e51-84c0-a72e3d486bba.png)

Generated mesh:

![mesh](https://user-images.githubusercontent.com/10292902/126846471-f4fffa2a-3bb5-42ea-82f5-1f0adad3f808.png)

[mesh_constraints_verts.txt](https://github.com/artem-ogre/CDT/files/6871425/mesh_constraints_verts.txt)
[mesh_constraints_edges.txt](https://github.com/artem-ogre/CDT/files/6871426/mesh_constraints_edges.txt)

**Comment by artem-ogre** [comment]
Thank you very much for taking the time and effort to create this issue.

I looked at your examples.
The triangulation result is correct: presence of 'cap' triangles indicates that three points are lying **almost but not exactly** on the same line. The triangulation algorithm relies internally on a numerically-robust predicate `orient2d(p, a, b)` which tells if `p` lies to the left, to the right, or **exactly** on line `ab`.

So in the last example, if you would change first coordinate of points to be exactly the same the 'cap' triangles should go away.

This property is highly desired as it guarantees that the triangulation will have correct topology for any possible inputs. Introducing tolerances to fix 'almost on the same line' can lead to wrong topologies.

If you would like to fix cap-triangles I can suggest writing some filtering step after the triangulation that removes 'cap' triangles by either removing them (e.g., when on the boundary) or by flipping 'cap' triangle's base edge (see image below).
![edge-flip](https://user-images.githubusercontent.com/7488293/126878497-220e0144-146c-45bb-8b5b-96125834eabb.png)

**Comment by artem-ogre** [comment]
Hope it explains your issue. I am closing it for now. If you have more questions or comments please don't hesitate.
