### ISSUE TITLE
Online documentation contains escaped output

### ISSUE THREAD

**Issue by HalfVoxel** [artem-ogre/CDT#68]
Looks like something has gone wrong when generating the docs.

![image](https://user-images.githubusercontent.com/1144597/147371691-ce5110ea-50c8-415a-a31d-0dd4ce2fabf6.png)

**Comment by artem-ogre** [comment]
Hi Aron, thank you for creating this issue.

The docs are generated with Doxygen. It has a feature of using a markdown file as a main page (`DOXYGEN_USE_MDFILE_AS_MAINPAGE`). This feature is used to to inject `README.md` into generated docs. Unfortunately this is how Doxygen renders it. 
I noticed this problem but I don't feel like putting time in resolving this. This could probably be done by either tweaking the README or fixing how Doxygen renders markdown (submitting a fix to Doxygen perhaps).
Any help is very welcome.

**Comment by artem-ogre** [comment]
Finally fixed, just check out this beauty: https://artem-ogre.github.io/CDT/
:)
