### ISSUE TITLE
bugs: duplicate point during triangulatePseudoPolygon are not handled

### ISSUE THREAD

**Issue by LeGamerDc** [artem-ogre/CDT#70]
according to paper,in insert edge step, there might be duplicate points of left point and right point. say we have a edge[1, 2], after eliminate triangle, we have [3, 4, 5, 4, 6] in left points, and we have a two triangle not tie right neighbor(of edge [4, 5]), so we must fix their neighbor after we do two triangulatePseudoPolygon.

since i'm not familiar with cpp, i could not give a merge request, sorry about that.

**Comment by artem-ogre** [comment]
Could you provide an image illustrating the issue perhaps? I am afraid I don’t follow your explanation.

**Comment by artem-ogre** [comment]
An input for reproducing the issue would be the best.

**Comment by LeGamerDc** [comment]
<img width="519" alt="企业微信截图_285d1f40-d54c-438b-8158-a206f713d9e6" src="https://user-images.githubusercontent.com/86505352/153787325-222f579b-5f9e-406e-a946-9e365ebe43c5.png">

take the graph from paper, we could find the Pu after eliminate triangle is [dedg], the vertex d appear twice. if later we triangulate result is tri (abe) (aed) (ebd) (dbg), then triangle (aed) and (ebd) would miss each other as neighbor.

**Comment by LeGamerDc** [comment]
so, we should find pattern [aba] in Pu and Pl, and fix the edge [ab]'s neighorship

**Comment by artem-ogre** [comment]
@LeGamerDc 
Hanging vertices situation is already handled properly in CDT. This exact case is represented in file [`Hanging.txt`](https://github.com/artem-ogre/CDT/blob/master/visualizer/data/Hanging.txt). You can run CDT on that input and inspect resulting triangles. All the neighboring information for the triangles should be set properly.

Please come back to confirm this or let me know if something is overlooked.
