### ISSUE TITLE
FR: Elevated Delaunay triangulation

### ISSUE THREAD

**Issue by stla** [artem-ogre/CDT#74]
Hello,

  This is an elevated Delaunay triangulation (also called 2.5D Delaunay triangulation):

![volcano](https://user-images.githubusercontent.com/4466543/156896108-81e9ff0f-0ad5-431a-b6de-cb4ca038852a.png)

It would be nice to have this feature. I personally do it by performing a 2D Delaunay triangulation of the (x,y)-coordinates of the points and then I add the z-coordinate, but it's possible that better strategies exist.

**Comment by artem-ogre** [comment]
Hello @stla,

1. Yes, that’s the intended way for producing the 2.5D surface: triangulate in 2D and use points’ heights as Z.
2. It looks like your example is a heightmap (aka DEM). In this case the heights are known for points placed on a regular grid. In this case you may skip Delaunay triangulation altogether as it is an overkill for the task at hand. Just connect points on grid into triangles with a regular pattern using neighboring points.

Something like this:
![](https://www.researchgate.net/profile/Robert-Fisher-3/publication/228539078/figure/fig17/AS:668347045802008@1536357761964/Triangulation-of-a-regular-grid-of-points.png)

**Comment by artem-ogre** [comment]
You may also check out [`initializeWithRegularGrid`](https://github.com/artem-ogre/CDT/blob/master/CDT/extras/InitializeWithGrid.h)

**Comment by stla** [comment]
Thanks, good to know that.

Are you sure there's not a better method than taking the (x,y)-coordinates and triangulate them, then adding the z height? I have been told (but vaguely) that one can project the 3D points on the best fitting plane, then triangulate on this plane and back-projecting. But that seems possibly problematic to me, because the projection on a plane can yield to duplicate points on this plane.

**Comment by artem-ogre** [comment]
Oh, yes, absolutely this can be done. 

The triangulation algorithms remain the same. Projection is therefore outside the scope of a triangulation library.

**Comment by stla** [comment]
You're right. So let's close.

FYI, I did a [R package](https://github.com/stla/RCDT) based on **CDT**.

**Comment by artem-ogre** [comment]
@stla 
That's nice, appreciate you letting me know!

One question, why GPL though? CDT is MPL-2.0 and it seems strange to restrict the usage when providing the bindings. It is totally your choice though how to license your code :)
In the case you stick with GPL could you add a clarification in your README that CDT itself is permissively licensed under MPL-2.0.  Thanks!

**Comment by artem-ogre** [comment]
Your DESCTIPTION, LICENSE and README are fine. What I am saying are just suggestions :)
What I was suggesting:
- If you don't have a preference then to re-license your package with MPL-2.0. This allows your package to be used in the wider range of applications including proprietary codebases.
- If you prefer GPL over MPL-2.0, then I would appreciate if you replace:
> It uses the C++ library [CDT](https://github.com/artem-ogre/CDT).

with

> It uses the C++ library [CDT](https://github.com/artem-ogre/CDT) which is permissively licensed under MPL-2.0.

**Difference between GPL and MPL-2:**

GPL is a copyleft license which means that derivative software (for example software using your R-package) needs to be distributed under the same or equivalent license terms. This means that your package would be impossible to use in any closed-source application.

MPL-2.0 is a more permissive weak-copyleft license characterized as a middle ground between permissive software licenses and the GPL. It allows the integration of MPL-licensed code into proprietary codebases, as long as the MPL-licensed components remain accessible under the terms of the MPL.

**Comment by stla** [comment]
Thank you! You learn me a lot.
I have already submitted this package to CRAN, I have to wait one month before submitting a new version. I will do the changes you suggest. I can already change the README.
