### ISSUE TITLE
Is there a situation where `fixedEdges` is useful?

### ISSUE THREAD

**Issue by stla** [artem-ogre/CDT#77]
Hello,

  As I understand, the constraint edges are given in `cdt.fixedEdges`. But the constraint edges are those that the user inserts in `cdt`, so he already knows them. Am I missing a case where `fixedEdges` is useful?

**Comment by artem-ogre** [comment]
Yes, it is useful in some corner cases. There are cases when fixed edges overlap (but don’t cross): 
imagine input points 0:(0,0) 1:(1,0) 2:(2,0) 3:(3,0) and constraint edges (0,2) (1,3).

CDT will handle this case properly and `fixedEdges` will contain (0,1) (1,2) (2,3)

**Comment by stla** [comment]
Ok, thank you for the reply.
